image: moussavdb/build-java

pipelines:
  default:
    - step:
        script:
          - mvn -V -B -s settings.xml package
  branches:
    master:
      - step:
          script:
            - mvn -V -B -s settings.xml package
